language: php

php:
    - 7.1
    - 7.2

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
    - sudo add-apt-repository ppa:ondrej/php -y
    - sudo apt-get -qq update
    - sudo apt-get install -y libsodium-dev

install:
    - printf "\n" | pecl install libsodium
    - composer install