---
name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  update-release-draft:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Run release drafter
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
