---
name: php-cs-fixer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Run php-cs-fixer
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: 🛠 Run php-cs-fixer
        uses: docker://oskarstark/php-cs-fixer-ga

      - name: 🤖 Apply php-cs-fixer changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply php-cs-fixer changes
